### ISSUE TITLE
добавить поддержку gRPC

### ISSUE THREAD

**Issue by beylkhanovdamir** [azaza12345/CsharpDapperExample#2]

**Comment by azaza12345** [comment]
Предоставил gRPC контракты (отдельную папочку в бизнес лоджик лейере найти можно), и добавил клиентик, через который запускал всё и тестил

**Comment by azaza12345** [comment]
В бизнес лейере добавил прото файлы для каждой сущности и реализовал gRPC контракты для всех crud операций, производимых с бд. Для проверки корректности работы, можно попробовать получить что-то, используя GrpcClient, содержащийся в проекте.
