### ISSUE TITLE
архитектура проекта должна быть хотя бы модульной

### ISSUE THREAD

**Issue by beylkhanovdamir** [azaza12345/CsharpDapperExample#3]

**Comment by azaza12345** [comment]
Разбил приложение на разные модули... указал между ними зависимости...

**Comment by azaza12345** [comment]
Разбил проект на разные модули: 
1) Entities - содержит в себе все сущности, используемые в приложении.
2) Infrastructure - слой существует для связи проекта с базой данных, в каждом репозитории содержатся реализации crud операций для определённой сущности.
3) BLL - слой содержит в себе сервисы, реализующие всю бизнес логику приложения
4) Web - view модуль, содержит в себе всё необходимое для отображения пользовательского интерфейса
5) ServicesUnitTestsApp - приложение с тестами бизнес логики
6) GrpcClient - клиентик, служащий исключительно для проверки корректности работы gRPC контрактов
